routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// //Halaman Login
Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    
    //Halaman Home
    Route::get('/','HomeController@index');

    //Halaman Master Kategori MAP (Mata Anggaran Penerimaan)
    Route::get('map_category/data','MapCategoryController@json');
    Route::Resource('map_category','MapCategoryController');

    //Halaman Master MAP (Mata Anggaran Penerimaan)
    Route::get('/map/data','MapController@json');
    Route::get('/map/check_map_id_exist','MapController@checkMapIdExist');
    Route::Resource('map','MapController');

    //Halaman Data Time Series
    //Halaman Input Data Time Series
    Route::get('/time_series/form','TimeSeriesController@form');
    Route::get('/time_series/download_format','TimeSeriesController@downloadFormat');
    Route::post('/time_series/load_excel','TimeSeriesController@loadExcel');
    Route::post('/time_series/store','TimeSeriesController@store');
    //Halaman Untuk Menampilkan Data Time Series
    Route::get('/time_series/data','TimeSeriesController@allTimeSeriesData');
    Route::get('/time_series/annual_data/{year}','TimeSeriesController@annualData');
    //Edit & Delete Data Time Series
    Route::get('/time_series/edit','TimeSeriesController@edit');
    Route::post('/time_series/update','TimeSeriesController@update');
    Route::post('/time_series/delete','TimeSeriesController@delete');
    //Plot Data Time Series
    Route::get('/time_series/plot_data','TimeSeriesController@plotData');
    Route::get('/time_series/get_plot_data','TimeSeriesController@getPlotData');

    //Halaman Foreacasting
    Route::get('/forecasting','ForecastingController@index');
    Route::get('/forecasting/calculate_forecasts','ForecastingController@calculateForecasts');

    //User
    Route::get('/user/data','UserController@json');
    Route::get('/user','UserController@index');
    Route::post('/user/store','UserController@store');
    Route::get('/user/edit/{id}','UserController@edit');
    Route::post('/user/update','UserController@update');
    Route::post('/user/update_password','UserController@updatePassword');
    Route::post('/user/delete','UserController@delete');
});

app/Http/Controllers/MapController.php
<?php

namespace App\Http\Controllers;

use App\MasterMap;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Response;

class MapController extends Controller{
    
    public function json(){
        return datatables()->of(MasterMap::get())->toJson();
    }

    public function index(){
        return view('modules/map/v_index');
    }
    
    public function store(Request $request){
        $id = $request->id_;

        //Map ID Must Unique
        if($id == ""){
            if(MasterMap::where('map_id', $request->map_id)->count() > 0){
                return "0";
            }
        }

        // Save/Update Operation
        $array_data = [
            'map_id' => $request->map_id,
            'map_name' => $request->map_name
        ];

        if($data = MasterMap::updateOrInsert(['map_id' => $id ], $array_data)){
            return "1";
        }else{
            return "0";
        }
    }
    
    public function edit($id){
        $where = array('map_id' => $id);
        $data  = MasterMap::where($where)->first();
 
        return Response::json($data);
    }
    
    public function destroy($id){
        $data = MasterMap::where('map_id',$id)->delete();
        return Response::json($data);
    }

    public function checkMapIdExist(Request $request){
        $map_id = $request->map;
        $status = true;
        $map_not_found = [];

        //Menghitung Jumlah Data
        for($i=0;$i<count($map_id);$i++){
            $count_of_data = MasterMap::where(['map_id' => $map_id[$i]])->count();
            if($count_of_data == 0){
                $status = false;
                array_push($map_not_found, $map_id[$i]);
            }
        }

        $return_data = [
            'status' => $status,
            'map_not_found' => $map_not_found
        ];

        return $return_data;


        
    }
}

resources/views/modules/map/v_index.blade.php
@extends('master_template')

@section('konten')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h5 class="card-title m-0"><b>Data Mata Anggaran Penerimaan</b></h5>
                        <div class="float-right">
                            <a href="{{ url('/') }}">Home</a> / MAP
                        </div>
                    </div>
                    <div class="card-body">
                        <div id="alert_" class="alert alert-info alert-dismissible fade show" role="alert">
                            <b id="alert_messages_">&nbsp;</b>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <button type="button" id="btnAddData" class="btn btn-primary btn-sm mb-2" data-toggle="modal" data-target="#modal_"><i class="fa fa-plus"></i> Tambah Data MAP</button>
                        <table class="table table-sm table-striped table-bordered" id="table_view">
                            <thead>
                                <tr>
                                    <td class="font-weight-bold text-center">No.</td>
                                    <td class="font-weight-bold text-center">Kode</td>
                                    <td class="font-weight-bold text-center">Nama MAP</td>
                                    <td class="font-weight-bold text-center">Aksi</td>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- Modal -->
<div class="modal fade" id="modal_" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form name="form_input" method="POST">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel"><b>Tambah Data MAP</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    <input type="hidden" name="id_" id="id_">
                    <div class="row">
                        <div class="col-md-6">
                            <small class="font-weight-bold">Kode MAP</small>
                            <input type="text" class="form-control form-control-sm" name="map_id" id="map_id" placeholder="Masukkan Kode MAP" />
                            <small id="kode_map_help_text" class="form-text text-danger"></small>
                        </div>
                        <div class="col-md-6">
                            <small class="font-weight-bold">Nama MAP</small>
                            <input type="text" class="form-control form-control-sm" name="map_name" id="map_name" placeholder="Masukkan Nama Kategori MAP" />
                        </div>
                    </div>
                
            </div>
            <div class="modal-footer">
                <button type="submit" id="btnSave" class="btn btn-primary btn-sm"><i class="fa fa-save"></i> Simpan</button>
            </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('konten_js')
<script>
    //Initialization - Loaded First
    $(function () {
        loadDataTable();
        $("#alert_").hide();
    });
    
    //CSRF Token
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    //Add New Data
    $('#btnAddData').on('click',function(event){
        $("#ModalLabel").addClass("font-weight-bold")
        $("#ModalLabel").html('Tambah Data MAP')
        emptyField();
    });

    //Save Data
    $('#btnSave').on('click', function(event) {
        event.preventDefault();

        //Check Kode Map, Must Have 6 Character
        if($("#map_id").val().length != 6 ){
            $("#kode_map_help_text").text("Kode Mata Anggaran Penerimaan harus 6 Karakter")
            return;
        }

        $.ajax({
            url : "{{ route('map.store') }}",
            method : "POST",
            data : {
                'id_' : $("#id_").val(),
                'map_id' : $("#map_id").val(),
                'map_name' : $("#map_name").val()
            },
            success : function(ajaxData){
                //Empty Field
                emptyField()
                //Hide Modal
                $("#modal_").modal('hide');
                //Modifikasi Alert                
                if(ajaxData == "1"){
                    $("#alert_messages_").text('Input Data Berhasil');
                }else{
                    $("#alert_messages_").text('Input Data Gagal');
                }
                $("#alert_").show();
                //Reload Table
                loadDataTable();
            }
        });
    });

    //Empty Field
    function emptyField(){
        $("#id_").val("")
        $("#map_id").val("")
        $("#map_name").val("")
    }

    //DataTable 
    function loadDataTable(){
        destroyDataTable();
        $("#table_view").DataTable({
            "responsive": true,
            "autoWidth": false,
            processing : true,
            serverSide : true,
            ajax : "{{ url('/map/data') }}",
            columns: [
                {render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }  
                },
                {data : 'map_id'},
                {data : 'map_name'},
                { "className" : "text-center",
                    render: function (data, type, row, meta) {
                        var action_button = "<button class='btn btn-sm btn-primary dropdown-toggle' type='button' id='dropdownMenuButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>Aksi </button>"+
                                "<div class='dropdown-menu' aria-labelledby='dropdownMenuButton'>"+
                                    "<a class='dropdown-item' href='#' onclick='edit("+row.map_id+")'>Edit</a>"+
                                    "<a class='dropdown-item' href='#' onclick='del("+row.map_id+")'>Delete</a>"+
                                "</div>";
                        return action_button;
                    }  
                },
            ],
        });
    }
    function destroyDataTable(){
        if ($.fn.DataTable.isDataTable('#table_view')) {
            $('#table_view').DataTable().destroy();
        }
        $('#table_view tbody').empty();
    }

    function edit(MapID){
        $("#modal_").modal('show');
        $("#ModalLabel").addClass("font-weight-bold")
        $("#ModalLabel").html('Edit Data MAP')
        $.ajax({
            type : "GET",
            url: "{{ url('map')}}"+"/"+MapID+"/"+"edit",
            success: function (ajaxData) {
                $("#id_").val(ajaxData.map_id)
                $("#map_id").val(ajaxData.map_id)
                $("#map_name").val(ajaxData.map_name)
            },
        });            
    }
    function del(MapID){
        if(confirm('Anda Yakin Menghapus Data?')){
            $.ajax({
                type : "DELETE",
                url: "{{ url('map')}}"+'/'+MapID,
                success: function (ajaxData) {
                    if(ajaxData == "1"){
                        $("#alert_messages_").text('Data Berhasil Dihapus');
                    }else{
                        $("#alert_messages_").text('Data Gagal Dihapus');
                    }
                    $("#alert_").show();
                    //Reload Table
                    loadDataTable();
                },
            });            
        }
    }
  </script>
@endsection